apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventstoreusers.josefbrandl.com
spec:
  group: josefbrandl.com
  names:
    kind: EventStoreUser
    listKind: EventStoreUserList
    plural: eventstoreusers
    shortNames:
    - esuser
    - esu
    singular: eventstoreuser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EventStoreUser is the Schema for the eventstoreusers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EventStoreUserSpec defines the desired state of EventStoreUser
          properties:
            eventStore:
              description: EventStore defines the Event Store on which the user should
                be created
              type: string
            groups:
              description: Groups defines the list of groups the Event Store user
                should belong to
              items:
                type: string
              type: array
          required:
          - eventStore
          type: object
        status:
          description: EventStoreUserStatus defines the observed state of EventStoreUser
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
