kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventstore-user-operator
subjects:
  - kind: ServiceAccount
    name: eventstore-user-operator
    namespace: eventstore-user-operator # ToDo: Template this
roleRef:
  kind: ClusterRole
  name: eventstore-user-operator
  apiGroup: rbac.authorization.k8s.io
