// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/josefbrandl/v1.EventStoreUser":       schema_pkg_apis_josefbrandl_v1_EventStoreUser(ref),
		"./pkg/apis/josefbrandl/v1.EventStoreUserSpec":   schema_pkg_apis_josefbrandl_v1_EventStoreUserSpec(ref),
		"./pkg/apis/josefbrandl/v1.EventStoreUserStatus": schema_pkg_apis_josefbrandl_v1_EventStoreUserStatus(ref),
	}
}

func schema_pkg_apis_josefbrandl_v1_EventStoreUser(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EventStoreUser is the Schema for the eventstoreusers API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/josefbrandl/v1.EventStoreUserSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/josefbrandl/v1.EventStoreUserStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/josefbrandl/v1.EventStoreUserSpec", "./pkg/apis/josefbrandl/v1.EventStoreUserStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_josefbrandl_v1_EventStoreUserSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EventStoreUserSpec defines the desired state of EventStoreUser",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"eventStore": {
						SchemaProps: spec.SchemaProps{
							Description: "EventStore defines the Event Store on which the user should be created",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"groups": {
						SchemaProps: spec.SchemaProps{
							Description: "Groups defines the list of groups the Event Store user should belong to",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"eventStore"},
			},
		},
	}
}

func schema_pkg_apis_josefbrandl_v1_EventStoreUserStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EventStoreUserStatus defines the observed state of EventStoreUser",
				Type:        []string{"object"},
			},
		},
	}
}
